### ISSUE TITLE
possibly read/write functions?

### ISSUE THREAD

**Issue by babaq** [JuliaLang/JLD.jl#11]
I have encountered a situation in which i have a array of anonymous functions that i want to save for later use.

but for now, the JLD complained that ```it cannot write a pointer to JLD file```.

I am curious that is it possible to do this, may be by save the function as an expression in some form of string and re-eval when read into current work space.

any thoughts?

**Comment by timholy** [comment]
This is probably possible to pull off, but will definitely take some exploration. A PR would be welcome :smile:. You may find some good tips about manipulating the AST in FastAnonymous.jl.

**Comment by amack315** [comment]
I'm new to Julia, but after digging around in reflection.jl, it appears that it's possible to store the lowered ASTs of functions as expressions, save the expressions in JLD, and then eval the expressions after loading from the JLD file to recover the original functions: 
```julia
using JLD

function func2expr(fun::Function)
	@assert !isa(fun.env, MethodTable) "function should be anonymous"
	ast = Base.uncompressed_ast(fun.code)
	Expr(:function, Expr(:tuple, ast.args[1]...), Expr(:block, ast.args[3].args...))
end

f = x -> 2x
ast_expr = func2expr(f)

@save "function.jld" ast_expr

@load "function.jld"
f_copy = eval(ast_expr)
```

This email thread covers a very similar issue and is helpful in understanding ASTs: https://groups.google.com/forum/#!topic/julia-users/SlCTBKOxzuU.

I am not acquainted with the JLD code, but it seems within the scope of the project to have JLD do this automatically.
