### ISSUE TITLE
MethodError with start

### ISSUE THREAD

**Issue by yakir12** [JuliaLang/JLD.jl#14]
Hi!
This might be due to the delayed Ubuntu builds for Julia Nightlies.
I get a `start` method error for this:
```julia
using JLD
save("a.jld", "a", Dict("a" => 1))
```
The error is:
```julia
ERROR: MethodError: `start` has no method matching start(::Type{Tuple{ASCIIString,Int64}})
```
My specs:
```Julia 
Version 0.4.0-dev+6095 (2015-07-20 14:38 UTC)
Commit c75f4d4* (27 days old master)
x86_64-linux-gnu
```

**Comment by garrison** [comment]
I am getting this as well on JuliaLang/julia@a6f1ee2. Bisect points to fb24c88.

**Comment by garrison** [comment]
However, on the latest julia `master` (JuliaLang/julia@77bef6e) everything works for me.

**Comment by yakir12** [comment]
Same here, everything works with the last git pull.


Yakir Gagnon
The Queensland Brain Institute (Building #79)
The University of Queensland
Brisbane QLD 4072
Australia

cell +61 (0)424 393 332
work +61 (0)733 654 089

**Comment by timholy** [comment]
Nice when bugs go away so easily. Thanks, @garrison!
