### ISSUE TITLE
Fix segfault on nightly

### ISSUE THREAD

**Issue by timholy** [JuliaLang/JLD.jl#22]
https://travis-ci.org/JuliaLang/JLD.jl/builds/80684396 suggests JLD may be segfaulting on nightly. Look into this.

**Comment by simonster** [comment]
It works on release-0.4 (although the JLDArchives tests are failing), so I'd guess it's the codegen rewrite. Backtrace on OS X is slightly better and looks like the same issue as simonster/JLD2.jl#3.

**Comment by vtjnash** [comment]
is this fixed now?

**Comment by simonster** [comment]
Now working locally.
