### ISSUE TITLE
Strange behaviour of a save()

### ISSUE THREAD

**Issue by AzamatB** [JuliaLang/JLD.jl#25]
I have a data set `data` which has a lot of redundancy. It is represented as 10x1 `Vector{Matrix{Float32}}`, where each element is approx. 150x5*10^6 `Matrix{Float32}`.
I can save it on my drive via `save("data.jld", "data", data)` with no problem. It takes approx. 30 GB of space and 10 min to complete the writing.

When I transform it to redundancy free representation as 130 entry `Dict{Int32, Vector{Float32}}` (call it `dic`) and 5*10^7x1 `Vector{Vector{Int32}}` (call it `arr`), where each element is 20-25x1 `Vector{Int32}` I am able to save the `dic` via `save("dic.jld", "dic", dic)`. However when I do the same for `arr`:  `save("arr.jld", "arr", arr)` it never finishes writing. This line has been running for 2 days and it is still not finished writing. This makes no sense to me because much larger `data` gets written in 10 mins.

**Comment by timholy** [comment]
Some objects don't save very nicely. To implement an efficient reader/writer, see the section in the manual on [custom serialization](https://github.com/JuliaLang/JLD.jl/blob/master/doc/jld.md#custom-serialization).
