### ISSUE TITLE
eltype not implemented for JldDataset

### ISSUE THREAD

**Issue by garrison** [JuliaLang/JLD.jl#28]
`eltype` is not implemented for `JldDataset`, which means `eltype(::JldDataset)` always returns `Any`.  This should be fixed, following [a similar definition in HDF5.jl](https://github.com/JuliaLang/HDF5.jl/blob/c324b4f7956c8bcf935c7129672a5267cb8d64f2/src/plain.jl#L903-L912).

**Comment by timholy** [comment]
Fixed in #33.
