### ISSUE TITLE
Type identity after reloading a module

### ISSUE THREAD

**Issue by uschmidt83** [JuliaLang/JLD.jl#54]
Hi, I have the problem that a type identity check via `isa` fails after I reload my custom type. Here's code to reproduce the issue:

```julia
# Foo.jl
module Foo
  type Bar
  end
end
```

```julia
using JLD
reload("Foo")

## store
x = Foo.Bar()
@save "data.jld" x

## load 1
reload("Foo")
@load "data.jld"
@show isa(x,Foo.Bar) # = true

## load 2
reload("Foo")
@load "data.jld"
@show isa(x,Foo.Bar) # = false
```
Shouldn't both `isa` calls return true?

Best,
Uwe

Julia version 0.4.3
JLD version 0.5.7

**Comment by timholy** [comment]
What happens if you also reload JLD?

**Comment by uschmidt83** [comment]
Hi Tim, both `isa` calls indeed return true when I do that:
```julia
reload("JLD")
reload("Foo")

## store
x = Foo.Bar()
JLD.@save "data.jld" x

## load 1
reload("Foo")
JLD.@load "data.jld"
@show isa(x,Foo.Bar) # = true

## load 2
reload("JLD")
reload("Foo")
JLD.@load "data.jld"
@show isa(x,Foo.Bar) # = true
```
I don't understand why though. Is this expected behavior?

Thanks,
Uwe

**Comment by timholy** [comment]
Yes. JLD ends up with its own notion of what `Foo` is, and if you reload one but not the other you have trouble.

**Comment by uschmidt83** [comment]
Thanks, Tim.

I've been coding in Julia for a few months now, but this is the first time that I've become aware that reloading only some of the modules may cause problems.

Does it mean I *should* always reload all modules during development, not just the one I'm actively working on? Or is there a better solution that only requires reloading the code that actually changed? The [workflow tips](http://docs.julialang.org/en/release-0.4/manual/workflow-tips/) section of the manual doesn't talk about these issues.

Uwe

**Comment by timholy** [comment]
You only have to worry about dependent modules: if B uses A, and you reload A, you need to reload B, too. The [Autoreload](https://github.com/malmaud/Autoreload.jl) package gets into some of the complexities.

I agree this is a pretty subtle case of dependencies, however.

**Comment by uschmidt83** [comment]
Thank you for the explanation and the pointer to the Autoreload package.

**Comment by 00sapo** [comment]
Just for reference, on modern versions, one should use:
```julia
using Revise
using JLD
revise(JLD)
```
