### ISSUE TITLE
Unit tests hang on OSX / current Julia master

### ISSUE THREAD

**Issue by rened** [JuliaLang/JLD.jl#6]
On current Julia master, the unit tests hang for me on OSX, with zero processor load:
```jl
Julia Version 0.4.0-dev+6479
Commit 8dcdf83* (2015-08-03 05:28 UTC)
Platform Info:
  System: Darwin (x86_64-apple-darwin13.4.0)
  CPU: Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
```
The unit tests for HDF5 pass. On Julia commit a2ed42c from about a month ago the JLD tests pass on OSX. On Linux the tests pass just as they should.
When hitting Ctrl-C Julia simply returns to the command line without any stack trace / info.

**Comment by timholy** [comment]
Can you `git bisect` Julia to see which commit broke it?

**Comment by rened** [comment]
https://github.com/JuliaLang/julia/commit/189a043dce16db seems to be the first commit where this happens on OSX.

**Comment by simonster** [comment]
I think renaming `jld.jl` should fix this. Right now `using JLD` causes it to load itself on case insensitive file systems.

**Comment by rened** [comment]
@simonster yes, you are right! just found that as well - shall I open an issue with julialang about this?

**Comment by simonster** [comment]
I think this is known in the discussion on #9079. It caused problems for other packages as well. For now we should just rename the file.

**Comment by rened** [comment]
ok, done: https://github.com/JuliaLang/JLD.jl/pull/8
